[project]
name = "rag-news-summarizer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "anthropic>=0.57.1",
    "beautifulsoup4>=4.13.4",
    "fastapi==0.115.6",
    "instructor>=1.10.0",
    "langchain>=0.3.26",
    "langchain-anthropic>=0.3.17",
    "langchain-core>=0.3.70",
    "langchain-voyageai>=0.1.4",
    "lxml>=6.0.0",
    "lxml-html-clean>=0.4.2",
    "newspaper4k>=0.9.3.1",
    "nltk>=3.9.1",
    "numpy>=2.3.1",
    "pip>=25.1.1",
    "pymilvus>=2.5.0",
    "pydantic>=2.11.7",
    "python-dateutil>=2.9.0.post0",
    "python-dotenv>=1.1.1",
    "ragas>=0.4.3",
    "requests>=2.32.4",
    "scikit-learn>=1.7.1",
    "streamlit>=1.47.0",
    "uvicorn[standard]==0.32.1",
    "voyageai>=0.3.5",
]
